### PR TITLE
Update IG for HDR1

### PR DESCRIPTION
**Pull request by SteveLLamb**
Updates to the Illustrated Guide to accommodate HDR1 as per:

https://github.com/ISDCF/registries/issues/475
https://github.com/ISDCF/registries/pull/488

### CODE REVIEW

**Review by palemieux — CHANGES_REQUESTED** [review]
`src/content/illustratedguide-int.md` should be an `.svg` file.

**Comment by SteveLLamb** [comment]
> `src/content/illustratedguide-int.md` should be an `.svg` file.

It is. The SVG code is embedded in the md file to render out to the page. This is the same it's been from the conversion.

**Comment by palemieux** [comment]
Why not give it an `svg` extension, like the PNG illustration has a `png` extension?

**Comment by palemieux** [comment]
I also suggest keeping the file name of the thumbnail constant so that GH generates a side-by-side diff.

**Comment by palemieux** [comment]
> `src/content/illustratedguide-int.md` should be an `.svg` file.

See https://github.com/ISDCF/registries-site/issues/66

**Review by palemieux — APPROVED** [review]

**Pull request merged**
