### PR TITLE
Enhancement/fullpage rendering

### PR DESCRIPTION
**Pull request by SteveLLamb**
Update to generate the entire DCNC site, rather than just the tables. Once pushed and merged, redirects from the current Wordpress pages will be added to the various pages as needed.

### CODE REVIEW

**Comment by SteveLLamb** [comment]
@palemieux @radford-for-smpte @japierce1028 This is finally ready for review. As noted in the PR description, this will replace all Wordpress pages, and redirects will be set up once approved and I merge into the master branch.

**Comment by SteveLLamb** [comment]
@japierce1028, I've posted the built version of this code to a temp folder for your checking at:
https://isdcf.com/newdcnc/build/

**Comment by japierce1028** [comment]
The new site at https://isdcf.com/newdcnc/build/ looks good. It will take some time to do the comparison. I suggest we post to isdcf.com/dcnc/ for it's permanent home? Then for a short time leave both sites working to make sure we did it right.

I'm looking for the source code for the pages. I'm blind. Could you give me a pointer to the acknowledgments source page and I should be able to find the rest.

**Comment by SteveLLamb** [comment]
> The new site at https://isdcf.com/newdcnc/build/ looks good. It will take some time to do the comparison. I suggest we post to isdcf.com/dcnc/ for it's permanent home? Then for a short time leave both sites working to make sure we did it right.
> 
> I'm looking for the source code for the pages. I'm blind. Could you give me a pointer to the acknowledgments source page and I should be able to find the rest.

https://registry-page.isdcf.com/ will be the permanent location once the master branch is merged. This location will be redirected from isdcf.com/dcnc/ (which currently redirects to https://www.isdcf.com/site/dcnc/, which will also be redirected to the new site in case anyone has linked either previous site links). I have it in a temp staging just for viewing. 

The source code for pages are divided into sections, via markdown (.md) files in /src/content/. This will be explained during the call to go over this. There will also be documentation available that is present in comments in the code for now, but will be pulled out into readme files.

**Comment by japierce1028** [comment]
I wonder if something else is going on. I go to /src/content and I don't find any markdown files ( https://github.com/ISDCF/registries-site/tree/master/src )

**Comment by SteveLLamb** [comment]
@japierce1028 the staging area has been updated at: https://isdcf.com/newdcnc/build/  The sitemap that links to all pages' section I was showing you is at https://github.com/ISDCF/registries-site/blob/enhancement/fullpage-rendering/src/content/readme.DCNCSiteMap.md

@radford-for-smpte @palemieux ready for review now. 

Any changes to text and/or anything else, please comment here, and I'll update.

**Comment by SteveLLamb** [comment]
@radford-for-smpte, @palemieux updated Lucidchart for Illustrated guide for readability. [https://lucid.app/lucidchart/2f97c7af-761d-4503-a695-0bca7f9df8ab/edit?shared=true&page=0_0#]

Page is rendered via exporting SVG from Lucid and directly pasting in the code for that into the MD file, rather than embed. I've put in a note at the top of the page, for updating the code slightly from Lucid, to get a full page render of the SVG, with "viewbox" and a class addition. Embed using iframe is not working well at all via direct share in Lucid or other means. Also, the SVG code can now be checked into GH, so that is a win. I think this is a better long term solution. 

@japierce1028 I've updated the staging area with the new Illustrated guide. Changes as noted above. Not all links in the chart currently work, as some pages are not live on the Master branch yet. 

I've removed the PDF direct link, as the page prints well as-is now.

**Review by palemieux — APPROVED** [review]

**Pull request merged**
